export const NOTIFY_PASSWORD_USER = "NOTIFY_PASSWORD_USER";
export const NOTIFY_EMAIL_USER = "NOTIFY_EMAIL_USER";
export const DISABLE_BALANCE_ON_ADD = 'DISABLE_BALANCE_ON_ADD';
export const DISABLE_BALANCE_ON_EDIT = 'DISABLE_BALANCE_ON_EDIT';
export const ALLOW_REGISTRATION = "ALLOW_REGISTRATION";
export const ALLOW_LOGIN = "ALLOW_LOGIN";